name: Release Stage Control

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Create Builds
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os:
          - 'windows'
        arch:
          - '386'
          - 'arm64'
          - 'amd64'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build Stage Control for GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} (${{matrix.arch}})
        run: |
          GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} go build -buildvcs -o dist/stage-contol-${{matrix.os}}-${{matrix.arch}} .
      - run: mv dist/stage-contol-${{matrix.os}}-${{matrix.arch}} dist/stage-contol-${{matrix.os}}-${{matrix.arch}}.exe
        if: ${{matrix.os == 'windows' }}
      - uses: actions/upload-artifact@v4
        with:
          name: stage-contol-${{matrix.os}}-${{matrix.arch}}-${{github.run_id}}
          path: |
            dist/**

  draft-release:
    name: Draft Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: stage-contol-*-*-${{github.run_id}}
          path: dist
          merge-multiple: true

      - uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.generate_changelog.outputs.changelog}}
          draft: true
          generate_release_notes: true
          files: |
            dist/**